### PR TITLE
Apple Silicon M1 / OSX ARM 64 Migration

### PR DESCRIPTION
**Pull request by fjetter**
Fixes https://github.com/conda-forge/numcodecs-feedstock/pull/67

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by fjetter** [comment]
cc @xhochy I created this PR since I wasn't allowed to push on https://github.com/conda-forge/numcodecs-feedstock/pull/67. Can you have a look? Does this mess up the bot somehow?

**Review by jrbourbeau — COMMENTED** [review]
Thanks @fjetter! cc @jakirkham

**Comment by xhochy** [comment]
The bot is happy with this, thanks!

**Comment by jakirkham** [comment]
Sorry missed this

**Pull request merged**
