### PR TITLE
Release 0.5.3

### PR DESCRIPTION
**Pull request by alimanfoo**

### CODE REVIEW

**Comment by alimanfoo** [comment]
Oops, forgot to update test dependencies in recipe.

**Comment by jakirkham** [comment]
Looks like we need to reset the build number too.

**Comment by jakirkham** [comment]
Took the liberty of pushing a commit to reset the build number. Hope that is ok. Otherwise LGTM.

**Comment by alimanfoo** [comment]
Of course, thanks - I'm always forgetting to reset the build number, need to write myself a reminder somewhere I can't miss it.

**Comment by alimanfoo** [comment]
@jakirkham is it cool to merge this given that the build on 9989e8d passed and there have only been trivial changes since?

**Comment by jakirkham** [comment]
Sure. Should be fine. Did a quick re-render in the last commit to update the project URL in the feedstock's README.

**Pull request merged**
